### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by Kelxe** [rf-peixoto/black_veil#1]
This can only be used in Linux? or is there some way to use on windows

**Comment by rf-peixoto** [comment]
Black Veil was created and is kept with Linux distributions in mind. Initially there is a trigger to report this on lines 24-25. If you comment them out or remove them, you can generate the file.output.py code and run it even in Windows. On lines 134 and 137, there are operating system commands that you should adapt to your system. Translating these commands is necessary if you want to export an executable file from PyInstaller.

However, removing lines 24 and 25 you can export file.output.py even in Windows. Then you can use any method you like to compile this code into an executable.exe. I would particularly recommend Nuitka: https://nuitka.net/

**Comment by rf-peixoto** [comment]
Okay, I didn't forget about this. Windows support has been added, alpha version. It can - and probably will - contain a lot of errors.
